# Generated by Django 4.1.2 on 2022-10-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.CharField(choices=[('G', 'All Ages'), ('PG', 'Parental Guidance'), ('PG-13', '13 or older'), ('R', 'Restricted'), ('UR', 'Unrated')], default='G', max_length=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movie')),
            ],
        ),
    ]
